services:
  - type: web
    name: etib-community-connect
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        sync: false
